export const TEXT = "text",
    SHORT_TEXT = "short-text",
    RADIO = "radio",
    SELECT = "select",
    SELECT_IMAGE = "select_image",
    SELECT_MULTIPLE = "select-multiple",
    INTEGER = "integer",
    FLOAT = "float",
    DATE = "date"