# Generated by Django 4.0.6 on 2022-09-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_service_url', models.CharField(max_length=150, verbose_name='Map Service URL')),
                ('options', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='display_method',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='template',
        ),
        migrations.AddField(
            model_name='question',
            name='is_geospatial',
            field=models.BooleanField(default=False, verbose_name='If the question must be answered geospatially or not'),
        ),
        migrations.AddField(
            model_name='survey',
            name='public_url',
            field=models.CharField(default='', max_length=150, verbose_name='Public URL'),
        ),
        migrations.AlterField(
            model_name='linestringlocation',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.answer'),
        ),
        migrations.AlterField(
            model_name='linestringlocation',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.question'),
        ),
        migrations.AlterField(
            model_name='pointlocation',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.answer'),
        ),
        migrations.AlterField(
            model_name='pointlocation',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.question'),
        ),
        migrations.AlterField(
            model_name='polygonlocation',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.answer'),
        ),
        migrations.AlterField(
            model_name='polygonlocation',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text (multiple line)'), ('short-text', 'short text (one line)'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'Select Multiple'), ('select_image', 'Select Image'), ('integer', 'integer'), ('float', 'float'), ('date', 'date')], default='text', max_length=150, verbose_name='Type of question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Question must be filled out'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='editable_answers',
            field=models.BooleanField(default=True, verbose_name='Answers can be edited after submission'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='need_logged_user',
            field=models.BooleanField(default=False, verbose_name='Only authenticated users have access to this survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='map_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.mapview'),
        ),
    ]
