# Generated by Django 4.0.6 on 2022-09-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='user',
            new_name='respondent',
        ),
    ]
