# Generated by Django 4.1.12 on 2023-11-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_response_respondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapview',
            name='geometries',
            field=models.JSONField(blank=True, null=True, verbose_name='Custom geometries for the map view'),
        ),
    ]
