# Generated by Django 4.0.6 on 2022-09-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_mapview_remove_answer_lat_remove_answer_lon_and_more'),
        ('apiapp', '0002_rename_user_response_respondent'),
    ]

    operations = [
    ]
