# Generated by Django 4.0.6 on 2022-08-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_rename_redirect_url_survey_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apiapp.survey'),
            preserve_default=False,
        ),
    ]
