# Generated by Django 4.1.12 on 2023-11-15 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_alter_mapview_geometries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='id',
        ),
        migrations.AlterField(
            model_name='response',
            name='interview_uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Unique ID of interview'),
        ),
    ]
