# Generated by Django 3.1.4 on 2022-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_merge_20220925_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='public_url',
            field=models.CharField(default='', max_length=255, verbose_name='Public URL'),
        ),
    ]
