# Generated by Django 5.0 on 2024-02-28 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_remove_response_id_alter_response_interview_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.AlterField(
            model_name='response',
            name='interview_uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Unique ID of interview'),
        ),
    ]
