# Generated by Django 4.0.6 on 2022-10-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_alter_answer_id_alter_linestringlocation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapview',
            name='name',
            field=models.CharField(default='Delft', max_length=150, verbose_name='Name of the MapView location'),
        ),
    ]
