# Generated by Django 5.0 on 2024-02-28 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_remove_answer_response_alter_response_interview_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(default='0122260b-3fcc-477e-85d2-fe43f0611100', on_delete=django.db.models.deletion.CASCADE, to='apiapp.response'),
            preserve_default=False,
        ),
    ]
