# Generated by Django 4.1.5 on 2023-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0006_mapview_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapview", name="options", field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="response",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date response was submitted"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last edit"),
        ),
    ]
