# Generated by Django 4.1.1 on 2023-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0007_alter_mapview_options_alter_response_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapview",
            name="geojson",
            field=models.JSONField(null=True),
        ),
    ]
