# Generated by Django 4.1.12 on 2023-11-03 15:58

import apiapp.models.mapview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_mapview_geojson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapview',
            name='geojson',
        ),
        migrations.AddField(
            model_name='mapview',
            name='geometries',
            field=models.JSONField(null=True, verbose_name='Custom geometries for the map view'),
        ),
        migrations.AlterField(
            model_name='mapview',
            name='map_service_url',
            field=models.CharField(default=apiapp.models.mapview.default_service_url, max_length=150, verbose_name='Map Service URL'),
        ),
        migrations.AlterField(
            model_name='mapview',
            name='options',
            field=models.JSONField(default=apiapp.models.mapview.default_options, verbose_name='Map service specific options'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
