# Generated by Django 5.0 on 2024-02-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_alter_answer_created_alter_answer_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='public_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Public URL'),
        ),
    ]
