# Generated by Django 4.0.6 on 2022-08-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Users can see it and answer it'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='need_logged_user',
            field=models.BooleanField(default=False, verbose_name='Only authenticated users can see it and answer it'),
        ),
    ]
