# Generated by Django 4.0.6 on 2022-08-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_design', '0002_alter_survey_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
    ]
